#ifndef _TCS_GLOBAL_H_
#define _TCS_GLOBAL_H_

#define DEFAULT_HEARTBEAT 30
#define DEFAULT_MAX_TIMEOUT_NUMS 3
#define DEFAULT_MAX_CONNCETIONS 5

#define MAX_SOCKET_BUFFER_LENGTH (64*1024)
#define SEND_BUF_SIZE 4096

#define MAX_DIRECT_LENGTH		1024

#endif