/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_detu_m1decoder_M1Decoder */

#ifndef _Included_com_detu_m1decoder_M1Decoder
#define _Included_com_detu_m1decoder_M1Decoder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_detu_m1decoder_M1Decoder_M1_DECODER_SIZE
#define com_detu_m1decoder_M1Decoder_M1_DECODER_SIZE 4L
/*
 * Class:     com_detu_m1decoder_M1Decoder
 * Method:    _setMediaCodecH264
 * Signature: ([Lcom/detu/m1decoder/MediaCodecH264;)V
 */
JNIEXPORT void JNICALL Java_com_detu_m1decoder_M1Decoder__1setMediaCodecH264
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_detu_m1decoder_M1Decoder
 * Method:    _start
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_detu_m1decoder_M1Decoder__1start
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     com_detu_m1decoder_M1Decoder
 * Method:    _stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_detu_m1decoder_M1Decoder__1stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_detu_m1decoder_M1Decoder
 * Method:    _refresh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_detu_m1decoder_M1Decoder__1refresh
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_detu_m1decoder_M1Decoder
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_detu_m1decoder_M1Decoder__1close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
