/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_detu_m1decoderdemo_M1FourRender */

#ifndef _Included_com_detu_m1decoderdemo_M1FourRender
#define _Included_com_detu_m1decoderdemo_M1FourRender
#ifdef __cplusplus
extern "C" {
#endif
#undef com_detu_m1decoderdemo_M1FourRender_RENDER_NUMBER
#define com_detu_m1decoderdemo_M1FourRender_RENDER_NUMBER 4L
/*
 * Class:     com_detu_m1decoderdemo_M1FourRender
 * Method:    _init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_detu_m1decoderdemo_M1FourRender__1init
  (JNIEnv *, jobject);

/*
 * Class:     com_detu_m1decoderdemo_M1FourRender
 * Method:    _start
 * Signature: (JLjava/lang/String;Z[Lcom/detu/m1decoder/MediaCodecH264;)V
 */
JNIEXPORT void JNICALL Java_com_detu_m1decoderdemo_M1FourRender__1start
  (JNIEnv *, jobject, jlong, jstring, jboolean, jobjectArray);

/*
 * Class:     com_detu_m1decoderdemo_M1FourRender
 * Method:    _refresh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_detu_m1decoderdemo_M1FourRender__1refresh
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_detu_m1decoderdemo_M1FourRender
 * Method:    _close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_detu_m1decoderdemo_M1FourRender__1close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_detu_m1decoderdemo_M1FourRender
 * Method:    _finalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_detu_m1decoderdemo_M1FourRender__1finalize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
